#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not foundit
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
