#!/usr/bin/env bash
#bad and good luck
C=1

while [ $C -lt 11 ]
do
	if [ $C -eq 4 ]
	then
		echo "bad luck"
	elif [ $C -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	C=$((C+1))
done
