#!/usr/bin/env bash
# 7 lines or less
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
sudo -u nginx service nginx start
